module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
	feather: require('./feather'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
	mx_stabilizer: require('./mx_stabilizer'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
	sharp_27: require('./sharp_27'),
	slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
}